/*
 * Copyright (c) 2023 santanu
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.appform.conductor.model.events;

import java.util.EnumSet;
import java.util.Set;

/**
 * Type of events
 */
public enum EventType {
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,
    USER_CREATED,
    USER_UPDATED,
    USER_STATE_CHANGED,
    USER_ROLE_ASSIGNED,
    USER_ROLE_REVOKED,
    USER_GROUP_ASSIGNED,
    USER_GROUP_UNASSIGNED,
    SKILL_CREATED,
    SKILL_UPDATED,
    SKILL_DELETED,
    SKILL_VALUE_ADDED,
    SKILL_VALUE_REMOVED,
    SKILL_VALUE_UPDATED,
    USER_SKILL_ASSOCIATED,
    USER_SKILL_DISACCOSIATED,
    USER_SESSION_UPDATED,
    USER_SESSION_CREATED,
    USER_ACTIVATION_TOKEN_GENERATED,
    USER_ACTIVATION_TOKEN_STATE_UPDATED,
    USER_PASSWORD_SET,
    USER_PASSWORD_FAILED_ATTEMPT_UPDATED,
    USER_PASSWORD_UPDATED,
    ADDRESS_CREATED,
    ADDRESS_DELETED,
    ADDRESS_UPDATED,
    SUBJECT_CREATED,
    SUBJECT_DELETED,
    SUBJECT_UPDATED,
    SUBJECT_IDENTIFIER_DELETED,
    SUBJECT_IDENTIFIER_CREATED,
    SUBJECT_IDENTIFIER_MARKED_PRIMARY,
    SUBJECT_IDENTIFIER_UPDATED,
    ACTION_DELETED,
    ACTION_CREATED,
    ACTION_UPDATED,
    SCHEMA_FIELD_ADDED,
    SCHEMA_FIELD_DELETED,
    SCHEMA_FIELD_UPDATED,
    SCHEMA_CREATED,
    SCHEMA_STATE_UPDATED,
    SCHEMA_DESCRIPTION_UPDATED,
    WORKFLOW_CREATED,
    WORKFLOW_DELETED,
    WORKFLOW_UPDATED,
    WORKFLOW_SELECTION_RULE_CHANGED,
    WORKFLOW_SELECTION_RULE_DELETED,
    WORKFLOW_STATE_CHANGED,
    WORKFLOW_STATE_DELETED,
    WORKFLOW_TRANSITION_DELETED,
    WORKFLOW_TRANSITION_CHANGED,
    ATTACHMENT_ADDED,
    ATTACHMENT_DELETED,
    COMMENT_ADDED,
    TICKET_CREATED,
    TICKET_UPDATED,
    TICKET_USER_ASSIGNED,
    TICKET_USER_UNASSIGNED,
    TICKET_GROUP_ASSIGNED,
    TICKET_EXTERNAL_REFERENCE_ID_UPDATED,
    TICKET_FIELDS_UPDATED,
    TICKET_PRIORITY_UPDATED,
    TICKET_STATE_UPDATED,
    RELATED_TICKET_ADDED,
    RELATED_TICKET_DELETED,
    REPORT_EXECUTION_COMPLETED,
    REPORT_CREATED,
    REPORT_STATE_UPDATED,
    REPORT_DELETED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED;
    public static final Set<EventType> ALL = EnumSet.allOf(EventType.class);
}
