/*
 * Copyright (c) 2021 Santanu Sinha
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.appform.conductor.usermgmt;

import at.favre.lib.crypto.bcrypt.BCrypt;
import com.google.common.base.Preconditions;
import com.google.common.base.Strings;
import com.google.common.collect.ImmutableMap;
import io.appform.conductor.error.ConductorErrorCode;
import io.appform.conductor.error.ConductorException;
import io.appform.conductor.usermgmt.model.*;
import io.appform.conductor.usermgmt.store.GroupStore;
import io.appform.conductor.usermgmt.store.SessionStore;
import io.appform.conductor.usermgmt.store.UserActivationTokenStore;
import io.appform.conductor.usermgmt.store.UserStore;
import io.appform.conductor.utils.StringUtils;
import lombok.extern.slf4j.Slf4j;
import lombok.val;

import javax.inject.Inject;
import javax.inject.Provider;
import java.util.*;
import java.util.stream.Collectors;

/**
 * User lifecycle manager
 */

@Slf4j
public class UserLifecycleManager {
    /**
     * Default validity for {@link UserActivationTokenStore.UserActivationToken}
     */
    private static final long DEFAULT_TOKEN_VALIDITY_MS = 86400_000; // 1 day

    /**
     * Default validity for {@link UserSession}
     */
    private static final long DEFAULT_SESSION_VALIDITY_MS = 7 * 86400_000; // 7 days

    /**
     * Once a user is in the following states, they cannot be reverted back or made actionable in any way
     */
    private static final EnumSet<UserState> TERMINAL_USER_STATES
            = EnumSet.of(UserState.BLACKLISTED, UserState.EXITED, UserState.DELETED);

    private final Provider<UserStore> userStore;
    private final Provider<UserActivationTokenStore> userActivationTokenStore;
    private final Provider<SessionStore> sessionStore;
    private final Provider<GroupStore> groupStore;

    @Inject
    public UserLifecycleManager(
            Provider<UserStore> userStore,
            Provider<UserActivationTokenStore> userActivationTokenStore,
            Provider<SessionStore> sessionStore,
            Provider<GroupStore> groupStore) {
        this.userStore = userStore;
        this.userActivationTokenStore = userActivationTokenStore;
        this.sessionStore = sessionStore;
        this.groupStore = groupStore;
    }

    /**
     * This will create an user and send an activation link for the user.
     * User will NOT be able to log in till activation is completed.
     * The state for the user will be {@link UserState#CREATED}
     *
     * @param name     User full name
     * @param email    User email id
     * @param password Password for the user
     * @return Materialized user details.
     */
    public Optional<UserSummary> createUser(String name, String email, String password) {
        final String userId = StringUtils.normalize(name);
        try {
            val userDetails = userStore.get()
                    .create(name, email, hash(password))
                    .orElse(null);
            if (null == userDetails) {
                log.error("Could not create user with email: {}", email);
                return Optional.empty();
            }
            return createToken(userId, userDetails);
        }
        catch (Exception e) {
            throw ConductorException.builder()
                    .errorCode(ConductorErrorCode.STORE_WRITE_ERROR)
                    .context(ImmutableMap.<String, Object>builder()
                                     .put("type", "users")
                                     .put("id", userId)
                                     .build())
                    .cause(e)
                    .build();
        }
    }

    /**
     * This function will activate a user basis the provided token and the supplied password.
     *
     * @param token    Activation token generated by {@link #createUser(String, String, String)}
     * @param password Password entered by user
     * @return Summary for a validated user
     */
    //TODO::EVENT
    public Optional<UserSession> activateUser(String token, String password) {
        if (Strings.isNullOrEmpty(token)) {
            log.error("Empty token passed for validation");
            return Optional.empty();
        }
        if (Strings.isNullOrEmpty(password)) {
            log.error("Empty password for token: {}", token);
            return Optional.empty();

        }
        val userToken = userActivationTokenStore.get().getById(token).orElse(null);
        if (null == userToken) {
            log.error("Invalid user activation token: {}", token);
            return Optional.empty();
        }
        if (userToken.getState().equals(UserActivationTokenStore.UserActivationTokenState.DELETED)) {
            log.error("Token {} is already deleted", token);
            return Optional.empty();
        }
        if (userToken.getState().equals(UserActivationTokenStore.UserActivationTokenState.VALIDATED)) {
            log.error("Token {} is already validated", token);
            return Optional.empty();
        }
        final Date currentDate = new Date();
        if (new Date(userToken.getCreated().getTime() + DEFAULT_TOKEN_VALIDITY_MS).before(currentDate)) {
            log.error("Token {} is expired. Created date: {} Current Date: {}",
                      token, userToken.getCreated(), currentDate);
            return Optional.empty();
        }

        val userId = userToken.getUserId();
        val user = validateUser(userId, password).orElse(null);
        if (null == user) {
            log.error("No valid user for token {} userID {}", token, userId);
            return Optional.empty();
        }

        val tokenUpdateStatus = userActivationTokenStore.get()
                .update(token, t -> {
                    t.setState(UserActivationTokenStore.UserActivationTokenState.VALIDATED);
                });
        if (!tokenUpdateStatus) {
            return Optional.empty();
        }
        log.info("Token {} successfully validated for user: {}", token, userId);
        if (user.getState().equals(UserState.CREATED)) {
            val updatedDetails = userStore.get().update(userId, userDetails -> {
                userDetails.setState(UserState.ACTIVE);
            }).orElse(null);
            if (null != updatedDetails) {
                return createSession(updatedDetails);
            }
        }
        log.warn("Token validated for user {} in state: {}", userId, user.getState());
        return createSession(user);
    }

    /**
     * Login a user and create a new session.
     * @param userId Userid for the user
     * @param password Password for the user
     * @return A new user session
     */
    public Optional<UserSession> loginUser(String userId, String password) {
        //Get a validated user
        val user = validateUser(userId, password).orElse(null);
        if (null == user) {
            return Optional.empty();
        }
        if (!user.getState().equals(UserState.ACTIVE)) {
            log.error("User {} is not ctive", userId);
            return Optional.empty();
        }

        return createSession(user);
    }

    /**
     * This will validate the session for a user
     * @param sessionId The id for the session that needs to be validated
     * @param userId the user id for which this session is present
     * @return True if a valid session, false otherwise
     */
    public boolean validateSession(String sessionId, String userId) {
        //TODO:: IMPLEMENT
        return false;
    }

    /**
     * Create a new {@link Group}
     * @param name name of the group
     * @param description description of the group
     * @return The newly created group
     */
    public Optional<Group> createGroup(String name, String description) {
        return groupStore.get()
                .create(name, description)
                .map(UserLifecycleManager::toGroup);
    }

    /**
     * Delete an existing {@link Group}
     * @param groupId ID for the existing group
     * @return The updated group with {@link Group#isDeleted()} set to true
     */
    public Optional<Group> deleteGroup(String groupId) {
        return groupStore.get()
                .delete(groupId)
                .map(UserLifecycleManager::toGroup);
    }

    /**
     * Add an {@link User} to a {@link Group}. A user can belong to multiple groups.
     * @param groupId ID for an existing group
     * @param userId ID for an existing user
     * @return Group information
     */
    public Optional<Group> addUserToGroup(String groupId, String userId) {
        val status = groupStore.get()
                .addUserToGroup(groupId, userId);
        log.info("User {} addition to group {}. Status: {}", groupId, userId, status);
        return groupStore.get()
                .get(groupId)
                .map(UserLifecycleManager::toGroup);
    }

    /**
     * Return a paginated list of users in the group
     * @param groupId ID for an existing group
     * @param start Start offset of the page
     * @param limit Number oif records to return
     * @return List of users in the group
     */
    public List<UserSummary> findUsersForGroup(String groupId, int start, int limit) {
        val groupStoreImpl = this.groupStore.get();
        val group = groupStoreImpl.get(groupId).orElse(null);
        if(null == group || group.isDeleted()) {
            return Collections.emptyList();
        }
        val userIds = groupStoreImpl
                .findUsersForGroup(groupId, start, limit);
        return userStore.get()
                .getByIds(userIds)
                .stream()
                .map(UserLifecycleManager::toSummary)
                .collect(Collectors.toList());
    }

    /**
     * Create a {@link Skill}
     * @param value The skill value
     * @return created Skill object
     */
    public Optional<Skill> createSkill(String value) {
        //TODO::IMPLEMENT
        return Optional.empty();
    }

    public Optional<Skill> deleteSkill(String skillId) {
        //TODO::IMPLEMENT
        return Optional.empty();
    }

    public boolean addUserSkill() {
        //TODO::IMPLEMENT
        return false;
    }

    public List<Skill> getSkillsForUser(String userId) {
        //TODO::IMPLEMENT
        return Collections.emptyList();
    }

    public List<UserSummary> getUsersWithSkill(String skillvalue) {
        //TODO::IMPLEMENT
        return Collections.emptyList();
    }

    private Optional<UserSession> createSession(UserStore.UserDetails user) {
        return sessionStore.get()
                .create(user.getId())
                .map(session -> {
                    val groupsForUser = groupStore.get()
                            .findGroupsForUser(user.getId())
                            .stream()
                            .map(UserLifecycleManager::toGroup)
                            .collect(Collectors.toSet());
                    return new UserSession(new User(toSummary(user), groupsForUser,
                                                             Collections.emptySet()), session.getId());
                });
    }

    private Optional<UserSummary> createToken(String userId, UserStore.UserDetails userDetails) {
        val token = userActivationTokenStore.get()
                .generate(userId, new Date(new Date().getTime() + DEFAULT_TOKEN_VALIDITY_MS))
                .orElse(null);
        if (null == token) {
            log.error("No token generated for user: {}", userId);
        }
        else {
            //TODO::SEND TOKEN OVER EMAIL
            log.info("Token for user: {} is [{}]", userId, token);
        }
        //TODO::SEND EVENT TO BUS
        return Optional.of(toSummary(userDetails));
    }

    private Optional<UserStore.UserDetails> validateUser(String userId, String password) {
        val user = userStore.get().getById(userId).orElse(null);
        ;
        if (null == user) {
            log.error("No valid user found for userID: {}", userId);
            return Optional.empty();
        }
        final boolean matchResult = matchHash(userId, password, user.getPassword());
        val updatedUser = userStore.get()
                .update(userId, userDetails -> {
                    val attempts = userDetails.getFailedPasswordAttempts() + 1;
                    if (matchResult) {
                        userDetails.setFailedPasswordAttempts(0);
                    }
                    else {
                        userDetails.setFailedPasswordAttempts(attempts);
                        if (attempts > 3) {
                            userDetails.setState(UserState.LOCKED);
                        }
                    }
                })
                .orElse(null);
        Preconditions.checkNotNull(updatedUser);
        if (matchResult) {
            log.info("User {} successfully authenticated", userId);
        }
        else {
            log.error("Password validation failure. User state for user {} is {} [attempts: {}]",
                      userId, updatedUser.getId(), updatedUser.getFailedPasswordAttempts());
        }
        return Optional.ofNullable(updatedUser)
                .filter(UserLifecycleManager::isUserActionable);
    }

    private static boolean isUserActionable(final UserStore.UserDetails userDetails) {
        return null != userDetails
                && !TERMINAL_USER_STATES.contains(userDetails.getState());
    }

    private static String hash(String s) {
        return BCrypt.withDefaults().hashToString(12, s.toCharArray());
    }

    private static boolean matchHash(String userId, String s, String hash) {
        val res = BCrypt.verifyer().verify(s.toCharArray(), hash);
        if (!res.verified) {
            //TODO::UPDATE RATE LIMIT COUNTER
            log.warn("Password validation failure for: {}. Error: {}", userId, res);
        }
        return res.verified;
    }

    private static UserSummary toSummary(UserStore.UserDetails user) {
        return new UserSummary(
                user.getId(),
                user.getName(),
                user.getEmail(),
                user.getState(),
                user.getCreated(),
                user.getUpdated());
    }

    private static Group toGroup(GroupStore.GroupDetails groupDetails) {
        return new Group(
                groupDetails.getId(),
                groupDetails.getName(),
                groupDetails.getDescription(),
                groupDetails.isDeleted(),
                groupDetails.getCreated(),
                groupDetails.getUpdated());
    }
}
